plugins: chroma acousticbrainz absubmit embedart fetchart lyrics replaygain mbsync copyartifacts info missing edit mpdstats mpdupdate

directory: /extra/home/Music/
library: /extra/home/Music/musiclibrary.blb
import:
    move: yes
chroma:
    auto: yes
acoustid:
    apikey: iVzJogWyXE
acousticbrainz:
    auto: yes
absubmit:
    auto: yes
copyartifacts:
    extensions: .mood
